version: '3.8'

services:
  macrosense-mcp-server:
    build: .
    container_name: macrosense-mcp-server
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=${PORT}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8000"